### ISSUE TITLE
No selections when empty CTSPROJECT

### ISSUE THREAD

**Issue by Plabbs** [ZEdwin/ZTCT#4]
In the constructor method the range me->project_trkorrs is populated from the table CTSPROJECT, but if that table is empty in the system then the range will be empty an all `WHERE NOT a~trkorr IN me->project_trkorrs` later in the program will return false and nothing is selected.

**Comment by ZEdwin** [comment]
If the range is empty, then it will return results... It only skips the transport numbers that are in the range. It used to be a problem in the past, because I used an EXCLUDE range and then selected all the transports with the statement WHERE trkorr IN project_trkorrs. That was an isue if the range was empty. Then, every transport was excluded. This could also be fixed by adding a dummy record in the Project_Range, but that was not the solution I preferred.
Now I use an INCLUDE range and verify if the selected transports are NOT in the project_trkorrs range. If the range is empty, no transports will be excluded.
Because it is really confusing, also for me, I tested this by commenting out the selection of projects in the Constructor and running the program. And I still got results. Even with an empty range...

**Comment by ZEdwin** [comment]
Oops. I now see I have an updated version in my current system. I'll upload it here ASAP.
I thought I had done this already. ARGH.

**Comment by ZEdwin** [comment]
It works... This used to be an issue in the past, but it has been solved some time ago.
Maybe you used an older version? To avoid confusion, I have created a new version with the atest code. This file can be found on the main page, and under releases (V3.0, Version 2019).

It should work... For me it does. During debugging I made sure the CTSPROJECT table was empty, and results were still collected.

**Comment by ZEdwin** [comment]
Should work... For me it does work, I made sure the CTS table was empty, and results were collected.

**Comment by Plabbs** [comment]
Ok, the new version seems to fix this 👍 
Thank you

**Comment by Plabbs** [comment]
I spoke too soon... there is still an issue.
Specifically in method "get_tps_for_same_object" there previous versions of the objects are not selected when me->project_trkorrs is empty.
I have tested this on my system and if I create a dummy entry in the range table then it selects correctly the previous versions of the object.

**Comment by ZEdwin** [comment]
Got it... Trying to prevent this with include/exclude and IN/NOT IN would be annoyingly complex in all occurences. I just re-implemented the previous solution (DUMMY record in the range).

Sometimes, it's better to keep things simple... Thanks @Plabbi for mentioning this bug!

The new version (Version 2019) now contains this fix, as wel as the nugget that can be found on the home page (which is always the latest version).

**Comment by Plabbs** [comment]
The new update fixes the problem for me.
I want to use the opportunity to thank you for a great program!

**Comment by ZEdwin** [comment]
Thanks, nice to hearing the problem is now fixed and that the program is useful!

I'll close the issue now. Cheers!
